version: '3'
services:
  redis:
    image: "redis"
    expose:
      - 6379
  web:
    image: "kevinzgdev/devops-project"
    command:  ["sh", "-c", "npm test && npm start"]
    ports:
      - "3000:3000"
    depends_on:
      - redis
    links:
      - redis
     