version: '3'
services:
  redis:
    image: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    hostname: redis-server
    ports:
     - "6379:6379"

  web:
    build: .
    ports:
      - "3000:3000"
    command: ["node", "userapi/src/index.js"]
    environment:
     - REDIS_HOST=redis-server
