---
- name: Install required packages
  yum:
    name:
      - curl
      - policycoreutils-python
      - openssh-server
    state: latest

- name: Install redis
  yum:
    name: redis
    state: latest

- name: Enable and start sshd
  service:
    name: sshd
    state: started
    enabled: yes

- name: Enable HTTP+HTTPS access
  firewalld:
    # This is how we use a variable
    service: "{{ item }}"
    permanent: yes
    state: enabled
  # The module will be run for each item
  with_items:
    - http
    - https

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: Install postfix
  yum:
    name: postfix
    state: latest

- name: Enable and start postfix
  service:
    name: postfix
    state: started
    enabled: yes

- name: Download node 17
  get_url:
    url: https://rpm.nodesource.com/setup_17.x
    dest: /opt
    mode: 755

- name: Setup node 17
  command: /opt/setup_17.x

- name: Install node
  yum:
    name: nodejs

- name: Install Node daemon to run it in background
  become: yes
  command: npm install pm2 -g
  args:
    chdir: /home/vagrant/project

- name: Install Node modules of the project
  become: no
  command: npm install
  args:
    chdir: /home/vagrant/project


