apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-host-path
  labels:
    app: devops-project-host-path
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project-host-path
  template:
    metadata:
      labels:
        app: devops-project-host-path
    spec:
      volumes:
        - name: my-hostpath
          hostPath:
            path: /mnt/hostPath/
            type: DirectoryOrCreate
      containers:
        - name: devops-project-container
          image: kevinzgdev/devops-project
          ports:
            - containerPort: 3000
              name: "http-server"
          volumeMounts:
            - name: my-hostpath
              mountPath: /devops-project-master
